server:
    port: 8083
spring:
    application:
        name: user-center

    datasource:
        url: jdbc:mysql://localhost:3306/demo?useUnide=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
        username: root
        password: root
        driver-class-name: com.mysql.cj.jdbc.Driver
        hikari:
            max-lifetime: 30000
            minimum-idle: 1
            maximum-pool-size: 20
            auto-commit: true
            idle-timeout: 10000
            connection-timeout: 30000
        type: com.zaxxer.hikari.HikariDataSource

    cloud:
      nacos:
        discovery:
          server-addr: localhost:8848
          metadata:
            instance: aa
            version: 1.0

management:
  endpoints:
      web:
        exposure:
          include: '*'
  endpoint:
    health:
        show-details: always