server:
  port: 8040
spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: 112.126.61.191:8848
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: path_route1
          uri: lb://user-center
          predicates:
            - Path=/user/**
        - id: path_route2
          uri: lb://content-center
          predicates:
            - Path=/share/**
        - id: path_route3
          uri: lb://content-center
          predicates:
            - Path=/notice/**
        - id: path_route4
          uri: lb://user-center
          predicates: # 断言，路径相匹配的进行路由
            - Path=/log/**


management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.springfranmework.cloud.gateway: trace
